name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup env
        run: echo MY_REPO_TOKEN=${{ secrets.MY_REPO_TOKEN }} > .env
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: pages
          gatsby-args: --prefix-paths
